### ISSUE TITLE
setting Popup's "Opened" property causes tool to fail

### ISSUE THREAD

**Issue by ellisonch** [EmptyKeys/UI_Generator#11]
I'm trying to run code when a popup is opened, as follows:
```
<Popup Opened="PopupOpened">
    <TextBlock>FooBarBaz</TextBlock>
</Popup>
```

The above causes the generator to fail, exiting with code -2.

The full error follows:
```

System.Windows.Markup.XamlParseException: 'Failed to create a 'Opened' from the text 'PopupOpened'.' Line number '18' and line position '461'. ---> System.Argum
entException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, Object target, String method, Boolean ignoreCase, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object target, String method)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateDelegateCritical(Type delegateType, Object target, String methodName)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateDelegate(Type delegateType, Object target, String methodName)
   at System.Xaml.EventConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value, XamlMember propert
y)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String
targetName, IAddLineInfo lineInfo)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject
, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at EmptyKeys.UserInterface.Generator.UserInterfaceGenerator.GenerateCode(String inputFileName, String inputFileContent, RenderMode renderMode, String desired
Namespace) in e:\!Prog\TFS\LogicMarbles\UIGenerator\UIGenerator\UserInterfaceGenerator.cs:line 55
System.Windows.Markup.XamlParseException: 'Failed to create a 'Opened' from the text 'PopupOpened'.' Line number '18' and line position '461'. ---> System.Argum
entException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, Object target, String method, Boolean ignoreCase, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object target, String method)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateDelegateCritical(Type delegateType, Object target, String methodName)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateDelegate(Type delegateType, Object target, String methodName)
   at System.Xaml.EventConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value, XamlMember propert
y)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String
targetName, IAddLineInfo lineInfo)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject
, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at EmptyKeys.UserInterface.Generator.UserInterfaceGenerator.GenerateCode(String inputFileName, String inputFileContent, RenderMode renderMode, String desired
Namespace) in e:\!Prog\TFS\LogicMarbles\UIGenerator\UIGenerator\UserInterfaceGenerator.cs:line 61
   at ekUiGen.Program.Generate(String xamlFile, String outputFile, RenderMode renderMode, String desiredNamespace) in e:\!Prog\TFS\LogicMarbles\UIGenerator\ekUi
Gen\Program.cs:line 170
   at ekUiGen.Program.Main(String[] args) in e:\!Prog\TFS\LogicMarbles\UIGenerator\ekUiGen\Program.cs:line 126
```

**Comment by EmptyKeys** [comment]
You can't use text in event as exception says. Try event trigger with Command or CommandPath (attached properties) - http://emptykeys.com/EmptyKeysUI/?topic=html/b4ca9479-08a7-08f4-f202-c91dd28ff574.htm

**Comment by ellisonch** [comment]
I was just going based on WPF examples.  In normal WPF, it appears you can set events the way I was trying to, and then it just looks for a method with that name with the right signature in your class.  I tried this with the default xaml=>cs compiler, and this is what it did.

It would be nice to handle that, or to make a decision that you will not.  That just means an error message.  Right now, when the tool exits like that, it is pretty much indistinguishable from a crash.

I only got that stack trace because I ran the tool on the command line instead of the default built event.  The normal error inside VS is just "error -2".  One thing you could do about this is generate an #error if your tool throws most exceptions, instead of failing.  This would make seeing the error a lot easier.

Obviously the best route would be to insert an #error like "We don't support using event names directly; please use event triggers with command or commandpath".  This is a pretty big task in general, but it might be easier to do one case at a time.  People trigger and report common problems first.

(I hope I'm not coming off abrasively; I'm just trying to figure things out and report problems I find.  Thanks for your help.)

**Comment by EmptyKeys** [comment]
I do not support code behind classes like WPF, but you can always create partial class of the same name and access controls directly. I would not recommend it tho.

Yeah, would be cool to be able detect that you used event etc. Unfortunately I'm using XamlReader Load method and if that crashes on some exception, I have no way knowing why (unless if I would somehow parse that exception, which is bad idea). I can generate #error line with exception tho.

**Comment by EmptyKeys** [comment]
Done, If there is crash on XAML load, exception message is generated in class output file. Avail in next version.
